/**
 * Design tokens: the brand's colours, fonts and radius in the formats a
 * developer or designer pastes straight in: CSS variables, a Tailwind theme
 * and W3C design-token JSON (imports into Figma via Tokens Studio).
 */
import { googleFontsHref, onColor, swatch } from './brand-system';
import { toSlug } from './text';
import type { BrandKit } from './types';

interface TokenSource {
  name: string;
  palette: BrandKit['identity']['palette'];
  typography: BrandKit['identity']['typography'];
  radius?: string;
}

const ROLES = ['ink', 'paper', 'brand', 'accent', 'tint'] as const;

/** A corner radius in px, read from the design-system sentence ("Soft 16px corners…"), default 14. */
function radiusPx(text?: string): number {
  const m = text?.match(/(\d{1,2})\s?px/);
  return m ? Number(m[1]) : 14;
}

export function cssTokens(t: TokenSource): string {
  const p = t.palette;
  const r = radiusPx(t.radius);
  const ty = t.typography;
  return [
    `/* ${t.name} design tokens: generated by GoBrandToday */`,
    `@import url('${googleFontsHref([ty.display, ty.body, ty.data])}');`,
    '',
    ':root {',
    ...ROLES.map((role) => `  --color-${role}: ${swatch(p, role)};`),
    ...ROLES.map((role) => `  --color-on-${role}: ${onColor(swatch(p, role))};`),
    `  --font-display: '${ty.display.family}', system-ui, sans-serif;`,
    `  --font-body: '${ty.body.family}', system-ui, sans-serif;`,
    `  --font-data: '${ty.data.family}', ui-monospace, monospace;`,
    `  --radius: ${r}px;`,
    `  --radius-sm: ${Math.max(4, Math.round(r / 2))}px;`,
    '  --space: 8px;',
    '}',
    '',
    'body { background: var(--color-paper); color: var(--color-ink); font-family: var(--font-body); }',
    'h1, h2, h3 { font-family: var(--font-display); letter-spacing: -0.03em; }',
    '.btn-primary { background: var(--color-brand); color: var(--color-on-brand); border-radius: var(--radius); }',
    '',
  ].join('\n');
}

export function tailwindTokens(t: TokenSource): string {
  const p = t.palette;
  const ty = t.typography;
  const r = radiusPx(t.radius);
  const colors = ROLES.map((role) => `        ${role}: '${swatch(p, role)}',`).join('\n');
  return `// ${t.name}: drop into tailwind.config.js (theme.extend). Generated by GoBrandToday.
module.exports = {
  theme: {
    extend: {
      colors: {
${colors}
      },
      fontFamily: {
        display: ['${ty.display.family}', 'system-ui', 'sans-serif'],
        body: ['${ty.body.family}', 'system-ui', 'sans-serif'],
        data: ['${ty.data.family}', 'ui-monospace', 'monospace'],
      },
      borderRadius: { brand: '${r}px' },
    },
  },
};
`;
}

/** W3C Design Tokens (DTCG) JSON. */
export function jsonTokens(t: TokenSource): string {
  const p = t.palette;
  const ty = t.typography;
  const color: Record<string, unknown> = {};
  for (const s of p) color[s.role] = { $type: 'color', $value: s.hex, $description: `${s.name}: ${s.usage}` };
  return JSON.stringify(
    {
      [toSlug(t.name) || 'brand']: {
        color,
        font: {
          display: { $type: 'fontFamily', $value: [ty.display.family, 'sans-serif'] },
          body: { $type: 'fontFamily', $value: [ty.body.family, 'sans-serif'] },
          data: { $type: 'fontFamily', $value: [ty.data.family, 'monospace'] },
        },
        radius: { $type: 'dimension', $value: `${radiusPx(t.radius)}px` },
      },
    },
    null,
    2,
  );
}

export function kitTokens(kit: BrandKit): TokenSource {
  return { name: kit.name, palette: kit.identity.palette, typography: kit.identity.typography, radius: kit.identity.designSystem.radius };
}
