"""Per-painting configuration: story, camera moves and music.

All wording comes from Dr Piyush Kiran Nayak's portfolio (catalogue plates N° 01-10).
Views are (cx, cy, width) in painting pixels; a scene moves from the first view to the second.
Elements are (cx, cy, crop size, label) shown in the round Mithila medallion.
"""

# Scene lengths in bars of the soundtrack (same for every reel).
SCENE_BARS = [("hook", 2), ("title", 2), ("story", 3), ("statement", 2), ("technique", 3),
              ("elements", 2), ("reveal", 2), ("artist", 3), ("cta", 3)]

CREDENTIALS = [
    "10+ years with Indian folk art",
    "Licensed artisan · Government of India",
    "Art educator · Urmila Setu Sansthan",
    "Studying at Shilp Kala Vidyapeeth",
]

PAINTINGS = {
    "01-amausa-ka-mela": dict(
        number="01",
        content=(40, 30, 1250, 903),
        shade=(8, 12, 30),
        hook=dict(views=[(548, 395, 400), (552, 420, 490)],
                  lines=["Two childhood friends.", "One river.", "One fair."]),
        title=dict(lines=["Amausa Ka Mela"], subtitle=("अमौसा का मेला", "deva"),
                   tags="FOLK LIFE  ·  FESTIVALS  ·  CONTEMPORARY MITHILA"),
        story=[dict(views=[(300, 430, 460), (330, 430, 460)], kicker="THE REUNION",
                    lines=["Champa & Chameli —", "childhood friends, together again"]),
               dict(views=[(770, 445, 460), (800, 445, 460)], kicker="AT A MELA IN PRAYAGRAJ",
                    lines=["trading stories of families,", "married lives and homes"])],
        statement=dict(views=[(575, 470, 490), (520, 560, 420)], kicker="THE GANGES BETWEEN THEM",
                       lines=["a river that has held", "their conversation", "in trust for years."]),
        technique=[dict(views=[(470, 250, 420), (640, 250, 420)], label="KACHNI",
                        lines=["Blue waves, hatched", "line by line"], note="patient, rhythmic linework"),
                   dict(views=[(905, 735, 470), (895, 715, 430)], label="BHARNI",
                        lines=["Solid colour fills", "that warm the figures"], note="acrylic on handmade paper")],
        elements=[(1118, 150, 300, "Birds in flight"), (150, 645, 270, "Floral fills"),
                  (905, 700, 300, "Geometric patterning"), (905, 470, 280, "Ornamental motifs")],
        reveal=dict(focus=(0.42, 0.42), kicker="INSPIRED BY THE POEM",
                    lines=["“Amausa Ka Mela”", "by Kailash Gautam"],
                    medium="ACRYLIC ON HANDMADE PAPER  ·  DIP NIB  ·  22 × 30 IN"),
        cta_view=(640, 470, 490),
        music="mela",
    ),
    "02-across-the-yamuna": dict(
        number="02",
        content=(30, 32, 1250, 905),
        shade=(10, 10, 10),
        hook=dict(views=[(640, 380, 380), (640, 450, 491)],
                  lines=["One midnight.", "One river.", "One act of devotion."]),
        title=dict(lines=["Across the Yamuna"], subtitle=("The Divine Journey", "serif-italic"),
                   tags="GODS & GODDESSES  ·  MYTHOLOGY"),
        story=[dict(views=[(640, 470, 440), (640, 450, 470)], kicker="THE MIDNIGHT CROSSING",
                    lines=["Vasudeva bears newborn", "Krishna across the Yamuna"]),
               dict(views=[(640, 340, 420), (660, 320, 440)], kicker="SHELTERED BY SHESHNAG",
                    lines=["Spread hoods shelter", "the child above the water"])],
        statement=dict(views=[(170, 460, 480), (1110, 460, 480)], kicker="DEVAKI & YASHODA",
                       lines=["Two mothers", "flank the scene —", "one child between them."]),
        technique=[dict(views=[(300, 600, 460), (360, 560, 460)], label="KATCHNI",
                        lines=["Rendered entirely in", "fine line & cross-hatching"],
                        note="black ink, no colour wash"),
                   dict(views=[(640, 470, 491), (640, 470, 420)], label="MANDALA FORMAT",
                        lines=["Concentric bands carry", "the story outward"], note="cosmological stillness")],
        elements=[(640, 330, 300, "Many-hooded Sheshnag"), (640, 640, 280, "Water in wavy lines"),
                  (190, 212, 250, "Corner medallions"), (245, 640, 260, "Leafy vines & hatching")],
        reveal=dict(focus=(0.5, 0.45), kicker="A NIGHT MITHILA REMEMBERS",
                    lines=["Line by patient line,", "in black ink alone"],
                    medium="ACRYLIC AND INK ON PAPER"),
        cta_view=(640, 470, 491),
        music="krishna",
    ),
    "03-nature-in-godna": dict(
        number="03",
        content=(22, 22, 890, 1258),
        shade=(36, 14, 6),
        hook=dict(views=[(470, 600, 420), (456, 640, 690)],
                  lines=["An ancient face.", "Ringed by leaves.", "Circled by life."]),
        title=dict(lines=["Nature in Godna"], subtitle=("Inspired by Chanu Devi", "serif-italic"),
                   tags="GODS & GODDESSES  ·  NATURE  ·  FOLK LIFE"),
        story=[dict(views=[(470, 610, 480), (470, 600, 440)], kicker="THE SOLAR FACE",
                    lines=["Neither fully human,", "nor fully celestial"]),
               dict(views=[(456, 300, 480), (456, 300, 520)], kicker="A PROCESSION OF LIFE",
                    lines=["Figures with raised arms", "and animals, in rhythm"])],
        statement=dict(views=[(456, 1000, 480), (456, 1000, 560)], kicker="ROOTED IN GODNA",
                       lines=["Stillness and rhythm,", "held in", "equal measure."]),
        technique=[dict(views=[(300, 480, 440), (600, 480, 440)], label="TIERED REGISTERS",
                        lines=["Rows of figures", "circle the centre"], note="rhythmic procession"),
                   dict(views=[(250, 780, 420), (300, 760, 380)], label="LEAF FILLER",
                        lines=["Every space alive", "with leaves"], note="dense leaf background filler")],
        elements=[(470, 610, 360, "Anthropomorphic sun"), (110, 150, 260, "Oval leaf border"),
                  (400, 1010, 260, "Triangular garments"), (770, 760, 300, "Striped tree trunks")],
        reveal=dict(focus=(0.5, 0.45), kicker="PAINTED WITH NATURE ITSELF",
                    lines=["Leaves, marigold, beetroot", "and banyan bark"],
                    medium="NATURAL PIGMENTS  ·  GOND BINDER  ·  22 × 30 IN"),
        cta_view=(456, 640, 690),
        music="tribal",
    ),
    "04-sawan": dict(
        number="04",
        content=(14, 14, 1266, 788),
        shade=(46, 6, 8),
        hook=dict(views=[(640, 560, 360), (640, 420, 435)],
                  lines=["Five women.", "One platter of bangles.", "All the joy of Sawan."]),
        title=dict(lines=["Sawan"], subtitle=("Women, Bangles, and Celebration", "serif-italic"),
                   tags="FESTIVALS  ·  FOLK LIFE"),
        story=[dict(views=[(260, 420, 435), (300, 420, 435)], kicker="THE MONSOON MONTH",
                    lines=["Marketplaces turn into", "laughter and colour"]),
               dict(views=[(1000, 420, 435), (1040, 420, 435)], kicker="AROUND THE BANGLE SELLER",
                    lines=["Choosing bangles together —", "a portrait of companionship"])],
        statement=dict(views=[(420, 400, 435), (860, 400, 435)], kicker="SHARED PLEASURE",
                       lines=["No hierarchy here —", "only shared", "delight."]),
        technique=[dict(views=[(640, 420, 435), (560, 420, 435)], label="KACHNI",
                        lines=["Disciplined black", "linework"], note="cross-hatched garments"),
                   dict(views=[(1180, 400, 435), (1150, 400, 435)], label="TRIANGLE BORDER",
                        lines=["A triangular border", "frames the quiet joy"], note="vines, birds and flowers")],
        elements=[(640, 630, 320, "Bangles"), (150, 200, 230, "Vines with birds"),
                  (640, 380, 240, "Jewellery & bindi"), (1060, 600, 280, "Patterned textiles")],
        reveal=dict(focus=(0.5, 0.5), kicker="CHOOSING BANGLES TOGETHER",
                    lines=["A portrait of", "feminine companionship"],
                    medium="ACRYLIC COLOURS ON HANDMADE SHEET  ·  DIP NIB  ·  A2"),
        cta_view=(640, 400, 435),
        music="sawan",
    ),
    "06-anvarat": dict(
        number="06",
        content=(10, 10, 1270, 857),
        shade=(12, 12, 12),
        hook=dict(views=[(440, 280, 340), (420, 430, 476)],
                  lines=["Keep moving.", "Keep rowing.", "Never cease."]),
        title=dict(lines=["Anvarat"], subtitle=("‘Unceasing’", "serif-italic"),
                   tags="FOLK LIFE  ·  NATURE"),
        story=[dict(views=[(260, 430, 476), (320, 430, 476)], kicker="THE MAYURPANKHI",
                    lines=["A woman steers", "a peacock-shaped boat"]),
               dict(views=[(820, 330, 476), (880, 330, 476)], kicker="ANVARAT  ·  UNCEASING",
                    lines=["Keep moving, press forward", "without ceasing"])],
        statement=dict(views=[(240, 430, 476), (240, 430, 420)], kicker="THE SUN AS WITNESS",
                       lines=["Forward movement,", "unhesitating,", "is itself complete."]),
        technique=[dict(views=[(640, 600, 476), (900, 600, 476)], label="KACHNI",
                        lines=["Water built from", "close striations"], note="rhythmic wavy lines"),
                   dict(views=[(950, 330, 476), (1000, 330, 420)], label="RED & BLACK",
                        lines=["A spare palette", "holds the composition"], note="dots stippled in solid black")],
        elements=[(190, 380, 300, "Peacock boat"), (130, 130, 230, "Anthropomorphic sun"),
                  (90, 60, 240, "Geometric border"), (560, 760, 260, "Katchni waves")],
        reveal=dict(focus=(0.4, 0.5), kicker="ANVARAT",
                    lines=["Continuity itself,", "made visible"],
                    medium="HANDMADE SHEET  ·  22 × 30 IN"),
        cta_view=(640, 430, 476),
        music="boat",
    ),
    "10-fire-does-not-consume-the-faithful": dict(
        number="10",
        content=(22, 26, 919, 1254),
        shade=(40, 6, 26),
        hook=dict(views=[(470, 560, 420), (470, 620, 690)],
                  lines=["The flames rise.", "The child prays.", "Faith holds."]),
        title=dict(lines=["Fire Does Not Consume", "the Faithful"], subtitle=("Holika & Prahlad", "serif-italic"),
                   tags="MYTHOLOGY  ·  GODS & GODDESSES  ·  FESTIVALS"),
        story=[dict(views=[(470, 450, 560), (470, 480, 600)], kicker="THE STORY BEHIND HOLI",
                    lines=["Holika carries Prahlad", "into the fire"]),
               dict(views=[(470, 620, 480), (470, 600, 520)], kicker="PRAHLAD IN PRAYER",
                    lines=["Hands folded,", "as flames push outward"])],
        statement=dict(views=[(700, 380, 520), (250, 380, 520)], kicker="THE FOUNDATION OF HOLI",
                       lines=["Fire does not", "consume", "the faithful."]),
        technique=[dict(views=[(720, 360, 480), (700, 330, 440)], label="BHARNI",
                        lines=["Flames pushed outward", "in magenta, red & yellow"], note="solid colour fills"),
                   dict(views=[(470, 1000, 420), (470, 1040, 390)], label="KATCHNI",
                        lines=["Hatched line-work", "grounds the composition"], note="dense parallel lines")],
        elements=[(200, 350, 300, "Swirling stylised fire"), (470, 255, 200, "Lotus motifs"),
                  (470, 510, 200, "Vaishnava tilak"), (75, 1180, 260, "Geometric border")],
        reveal=dict(focus=(0.5, 0.4), kicker="THE STORY OF HOLI",
                    lines=["Devotion, held calm", "against destruction"],
                    medium="HANDMADE SHEET  ·  DIP NIB  ·  22 × 30 IN"),
        cta_view=(470, 640, 690),
        music="holi",
    ),
}
