'use client';

import { useEffect, useState, type ReactNode } from 'react';
import { googleFontsHref, type GoBrandScore } from '@gbt/shared';
import { useApp } from '@/lib/providers';
import { Footer } from './Footer';
import { Nav } from './Nav';
import { Spark, SparkLoader } from './Spark';

export function Shell({ children, footer = true }: { children: ReactNode; footer?: boolean }) {
  return (
    <>
      <Nav />
      <main id="main">{children}</main>
      {footer && <Footer />}
    </>
  );
}

export function SourceBadge({ source }: { source: 'ai' | 'offline' | string }) {
  const { system } = useApp();
  if (source === 'ai')
    return (
      <span className="badge" title={system?.ai.model}>
        <Spark size={10} /> AI
      </span>
    );
  return (
    <span className="badge amber" title="Generated by our rule-based engine because no AI provider is connected">
      Offline generator
    </span>
  );
}

export function DemoBanner() {
  const { system } = useApp();
  if (!system || system.mode !== 'demo') return null;
  return (
    <div className="notice warn" role="note">
      <strong>Demo mode.</strong> Domain and handle results are sample data, clearly marked “demo” — not real availability.
    </div>
  );
}

/* --------------------------------- score --------------------------------- */

export function ScorePill({ score }: { score: GoBrandScore }) {
  return (
    <span className={`score-pill ${score.provisional ? 'provisional' : ''}`} title={score.provisional ? 'Provisional — check domains & handles to complete the score' : 'GoBrand Score'}>
      {score.provisional ? '~' : ''}
      {score.overall.toFixed(1)}
      <small>/10</small>
    </span>
  );
}

export function ScoreCard({ score, sample }: { score: GoBrandScore; sample?: boolean }) {
  return (
    <div className="scorecard">
      <div className="stack gap-4">
        <span className="label">GOBRAND SCORE{score.provisional ? ' · PROVISIONAL' : ''}</span>
        <span className="value">
          {score.overall.toFixed(1)}
          <small> / 10</small>
        </span>
      </div>
      <span className="mono tiny" style={{ color: '#19C3B4' }}>
        {sample ? 'SAMPLE' : score.provisional ? 'CHECKS PENDING' : 'VERIFIED INPUTS'}
      </span>
    </div>
  );
}

export function ScoreBreakdown({ score, compact }: { score: GoBrandScore; compact?: boolean }) {
  return (
    <div className="stack gap-12">
      {score.components.map((c) => (
        <div key={c.key} className="stack gap-6">
          <div className="row between gap-12">
            <span style={{ fontWeight: 700, fontSize: 14.5 }}>{c.label}</span>
            <span className="mono small">{c.value === null ? '—' : c.value.toFixed(1)}</span>
          </div>
          <div className={`bar ${c.value === null ? 'pending' : ''}`}>
            <span style={{ width: `${(c.value ?? 0) * 10}%` }} />
          </div>
          {!compact && <span className="tiny muted">{c.note}</span>}
        </div>
      ))}
      <p className="tiny muted">
        Weights: {score.components.map((c) => `${c.label} ${c.weight}%`).join(' · ')}. The score is guidance — not a guarantee of trademark clearance, search rankings or success.
      </p>
    </div>
  );
}

export function Risks({ score }: { score: GoBrandScore }) {
  const risks = score.risks.filter((r) => r.level !== 'info');
  if (!risks.length) return null;
  return (
    <div className="stack gap-8">
      {risks.map((r) => (
        <div key={r.message} className={`notice ${r.level === 'high' ? 'error' : 'warn'}`}>
          {r.message}
        </div>
      ))}
    </div>
  );
}

/* ------------------------------ misc helpers ------------------------------ */

export function Loading({ title, steps }: { title: string; steps?: string[] }) {
  const [i, setI] = useState(0);
  useEffect(() => {
    if (!steps?.length) return;
    const t = setInterval(() => setI((x) => (x + 1) % steps.length), 1800);
    return () => clearInterval(t);
  }, [steps]);
  return (
    <div className="stack gap-16 center" style={{ alignItems: 'center', padding: '48px 16px' }} aria-busy="true">
      <SparkLoader size={80} />
      <div className="stack gap-6" style={{ alignItems: 'center' }}>
        <strong className="display" style={{ fontSize: 24 }}>
          {title}
        </strong>
        {steps && (
          <span key={i} className="muted fade-up">
            {steps[i]}
          </span>
        )}
      </div>
    </div>
  );
}

export function CopyButton({ text, label = 'Copy' }: { text: string; label?: string }) {
  const { toast } = useApp();
  return (
    <button
      type="button"
      className="btn btn-ghost btn-xs no-print"
      onClick={() => {
        navigator.clipboard?.writeText(text).then(
          () => toast('Copied'),
          () => toast('Could not copy', 'error'),
        );
      }}
    >
      {label}
    </button>
  );
}

/** Load Google Fonts for a user brand on demand. */
export function useGoogleFonts(families: Array<{ family: string; weights: number[] }> | undefined) {
  const key = families?.map((f) => `${f.family}:${f.weights.join(',')}`).join('|');
  useEffect(() => {
    if (!families?.length) return;
    const href = googleFontsHref(families);
    if (document.querySelector(`link[data-gf="${CSS.escape(href)}"]`)) return;
    const link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = href;
    link.dataset.gf = href;
    document.head.appendChild(link);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [key]);
}

export function Empty({ title, body, action }: { title: string; body?: string; action?: ReactNode }) {
  return (
    <div className="card center stack gap-12" style={{ alignItems: 'center', padding: '48px 24px' }}>
      <Spark size={28} />
      <strong className="display" style={{ fontSize: 22 }}>
        {title}
      </strong>
      {body && <p className="muted" style={{ maxWidth: 420 }}>{body}</p>}
      {action}
    </div>
  );
}
