'use client';

import { useEffect, useState, type ReactNode } from 'react';
import {
  SOCIAL_PLATFORMS,
  googleFontsHref,
  type DomainResult,
  type GoBrandScore,
  type HandleSuggestion,
  type SocialResult,
} from '@gbt/shared';
import { track } from '@/lib/api';
import { useApp } from '@/lib/providers';
import { Footer } from './Footer';
import { Nav } from './Nav';
import { Spark, SparkLoader } from './Spark';

export function Shell({ children, footer = true }: { children: ReactNode; footer?: boolean }) {
  return (
    <>
      <Nav />
      <main id="main">{children}</main>
      {footer && <Footer />}
    </>
  );
}

/* ------------------------------- statuses ------------------------------- */

const DOMAIN_LABEL: Record<DomainResult['status'], string> = {
  available: 'Available',
  taken: 'Taken',
  premium: 'Premium',
  unknown: 'Unverified',
  invalid: 'Not allowed',
};

export function DomainStatus({ r }: { r: DomainResult }) {
  const demo = r.source === 'demo';
  const title = [r.note, r.verified ? `Verified via ${sourceLabel(r.source)}` : demo ? 'Demo data — not a real check' : 'Not verified'].filter(Boolean).join(' · ');
  return (
    <span className={`status ${r.status} ${demo ? 'demo' : ''}`} title={title}>
      {DOMAIN_LABEL[r.status]}
    </span>
  );
}

export function sourceLabel(s: string): string {
  return (
    { rdap: 'the registry (RDAP)', dns: 'DNS', godaddy: 'GoDaddy', hostinger: 'Hostinger', namecheap: 'Namecheap', demo: 'demo data' } as Record<string, string>
  )[s] ?? s;
}

const SOCIAL_LABEL: Record<SocialResult['status'], string> = {
  available: 'Available',
  taken: 'Taken',
  unknown: 'Unverified',
  invalid: 'Not allowed',
  manual: 'Check ↗',
};

export function SocialStatus({ r }: { r: SocialResult }) {
  const demo = r.method === 'demo';
  if (r.status === 'manual') {
    return (
      <a className="status manual" href={r.url} target="_blank" rel="noopener noreferrer" title={r.note} onClick={() => track('social_checked', { platform: r.platform, manual: true })}>
        Check ↗
      </a>
    );
  }
  return (
    <span className={`status ${r.status} ${demo ? 'demo' : ''}`} title={r.note}>
      {SOCIAL_LABEL[r.status]}
    </span>
  );
}

export function SourceBadge({ source }: { source: 'ai' | 'offline' | string }) {
  const { system } = useApp();
  if (source === 'ai')
    return (
      <span className="badge" title={system?.ai.model}>
        <Spark size={10} /> AI
      </span>
    );
  return (
    <span className="badge amber" title="Generated by our rule-based engine because no AI provider is connected">
      Offline generator
    </span>
  );
}

export function DemoBanner() {
  const { system } = useApp();
  if (!system || system.mode !== 'demo') return null;
  return (
    <div className="notice warn" role="note">
      <strong>Demo mode.</strong> Domain and handle results are sample data, clearly marked “demo” — not real availability.
    </div>
  );
}

/* --------------------------------- score --------------------------------- */

export function ScorePill({ score }: { score: GoBrandScore }) {
  return (
    <span className={`score-pill ${score.provisional ? 'provisional' : ''}`} title={score.provisional ? 'Provisional — check domains & handles to complete the score' : 'GoBrand Score'}>
      {score.provisional ? '~' : ''}
      {score.overall.toFixed(1)}
      <small>/10</small>
    </span>
  );
}

export function ScoreCard({ score, sample }: { score: GoBrandScore; sample?: boolean }) {
  return (
    <div className="scorecard">
      <div className="stack gap-4">
        <span className="label">GOBRAND SCORE{score.provisional ? ' · PROVISIONAL' : ''}</span>
        <span className="value">
          {score.overall.toFixed(1)}
          <small> / 10</small>
        </span>
      </div>
      <span className="mono tiny" style={{ color: '#19C3B4' }}>
        {sample ? 'SAMPLE' : score.provisional ? 'CHECKS PENDING' : 'VERIFIED INPUTS'}
      </span>
    </div>
  );
}

export function ScoreBreakdown({ score, compact }: { score: GoBrandScore; compact?: boolean }) {
  return (
    <div className="stack gap-12">
      {score.components.map((c) => (
        <div key={c.key} className="stack gap-6">
          <div className="row between gap-12">
            <span style={{ fontWeight: 700, fontSize: 14.5 }}>{c.label}</span>
            <span className="mono small">{c.value === null ? '—' : c.value.toFixed(1)}</span>
          </div>
          <div className={`bar ${c.value === null ? 'pending' : ''}`}>
            <span style={{ width: `${(c.value ?? 0) * 10}%` }} />
          </div>
          {!compact && <span className="tiny muted">{c.note}</span>}
        </div>
      ))}
      <p className="tiny muted">
        Weights: {score.components.map((c) => `${c.label} ${c.weight}%`).join(' · ')}. The score is guidance — not a guarantee of trademark clearance, search rankings or success.
      </p>
    </div>
  );
}

export function Risks({ score }: { score: GoBrandScore }) {
  const risks = score.risks.filter((r) => r.level !== 'info');
  if (!risks.length) return null;
  return (
    <div className="stack gap-8">
      {risks.map((r) => (
        <div key={r.message} className={`notice ${r.level === 'high' ? 'error' : 'warn'}`}>
          {r.message}
        </div>
      ))}
    </div>
  );
}

/* ------------------------------ domain table ------------------------------ */

export function DomainTable({ results, onWatch }: { results: DomainResult[]; onWatch?: (d: DomainResult) => void }) {
  return (
    <div className="table-scroll">
      <table className="table">
        <thead>
          <tr>
            <th>Domain</th>
            <th>Status</th>
            <th className="hide-sm">Checked with</th>
            <th style={{ textAlign: 'right' }}>Get it</th>
          </tr>
        </thead>
        <tbody>
          {results.map((r) => (
            <tr key={r.domain}>
              <td className="mono" style={{ fontSize: 15 }}>
                {r.domain}
                {r.price && (
                  <div className="tiny muted">
                    {new Intl.NumberFormat('en-IN', { style: 'currency', currency: r.price.currency }).format(r.price.amount)}
                  </div>
                )}
              </td>
              <td>
                <DomainStatus r={r} />
                {r.note && r.status !== 'taken' && <div className="tiny muted" style={{ marginTop: 6, maxWidth: 300 }}>{r.note}</div>}
              </td>
              <td className="hide-sm tiny muted">{r.verified ? `✓ ${sourceLabel(r.source)}` : r.source === 'demo' ? 'Demo data' : 'Not verified'}</td>
              <td style={{ textAlign: 'right' }}>
                {r.buyLinks.length > 0 ? (
                  <BuyMenu r={r} />
                ) : r.status === 'taken' && onWatch ? (
                  <button className="btn btn-ghost btn-xs" onClick={() => onWatch(r)}>
                    Watch
                  </button>
                ) : (
                  <span className="tiny muted">—</span>
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function BuyMenu({ r }: { r: DomainResult }) {
  const [primary, ...rest] = r.buyLinks;
  if (!primary) return null;
  return (
    <div className="row gap-6" style={{ justifyContent: 'flex-end', flexWrap: 'wrap' }}>
      <a
        className="btn btn-primary btn-xs"
        href={primary.url}
        target="_blank"
        rel="noopener noreferrer sponsored"
        onClick={() => track('purchase_link_clicked', { domain: r.domain, registrar: primary.registrar })}
      >
        {r.status === 'unknown' ? 'Check on' : 'Buy on'} {primary.label}
      </a>
      {rest.map((l) => (
        <a
          key={l.registrar}
          className="btn btn-ghost btn-xs"
          href={l.url}
          target="_blank"
          rel="noopener noreferrer sponsored"
          onClick={() => track('purchase_link_clicked', { domain: r.domain, registrar: l.registrar })}
        >
          {l.label}
        </a>
      ))}
    </div>
  );
}

/* ------------------------------ social grid ------------------------------ */

const PLATFORM_ICON: Record<string, string> = {
  instagram: 'IG',
  x: '𝕏',
  youtube: 'YT',
  linkedin: 'in',
  tiktok: 'TT',
  facebook: 'f',
  threads: '@',
  pinterest: 'P',
  reddit: 'r/',
  github: 'GH',
};

export function SocialGrid({ results }: { results: SocialResult[] }) {
  return (
    <div className="grid-2" style={{ gap: 10 }}>
      {results.map((r) => {
        const p = SOCIAL_PLATFORMS.find((x) => x.id === r.platform);
        return (
          <div key={r.platform} className="row between gap-12" style={{ border: '1px solid var(--line)', borderRadius: 14, padding: '10px 12px', background: '#fff' }}>
            <div className="row gap-10" style={{ minWidth: 0 }}>
              <span
                aria-hidden="true"
                className="mono"
                style={{ width: 34, height: 34, borderRadius: 10, background: 'var(--paper)', border: '1px solid var(--line)', display: 'grid', placeItems: 'center', fontSize: 12, fontWeight: 700, flex: 'none' }}
              >
                {PLATFORM_ICON[r.platform]}
              </span>
              <div className="stack" style={{ minWidth: 0 }}>
                <span style={{ fontWeight: 700, fontSize: 14.5 }}>{p?.label}</span>
                <a href={r.url} target="_blank" rel="noopener noreferrer" className="mono tiny muted" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                  @{r.handle}
                </a>
              </div>
            </div>
            <SocialStatus r={r} />
          </div>
        );
      })}
    </div>
  );
}

export function Alternatives({ items }: { items: HandleSuggestion[] }) {
  if (!items.length) return null;
  return (
    <div className="stack gap-10">
      <div className="row gap-8 wrap">
        <strong style={{ fontSize: 15 }}>Close alternatives</strong>
        <span className="tiny muted">Suggestions — marked “verified” only where we could check them.</span>
      </div>
      <div className="chips">
        {items.map((a) => (
          <span key={a.handle} className="chip static sm" title={a.verifiedOn.length ? `Verified available on ${a.verifiedOn.join(', ')}` : 'Suggestion — not verified'}>
            <span className="mono">@{a.handle}</span>
            {a.verifiedOn.length > 0 ? (
              <span className="badge aqua" style={{ fontSize: 10 }}>
                ✓ {a.verifiedOn.length}
              </span>
            ) : (
              <span className="badge line" style={{ fontSize: 10 }}>
                idea
              </span>
            )}
          </span>
        ))}
      </div>
    </div>
  );
}

/* ------------------------------ misc helpers ------------------------------ */

export function Loading({ title, steps }: { title: string; steps?: string[] }) {
  const [i, setI] = useState(0);
  useEffect(() => {
    if (!steps?.length) return;
    const t = setInterval(() => setI((x) => (x + 1) % steps.length), 1800);
    return () => clearInterval(t);
  }, [steps]);
  return (
    <div className="stack gap-16 center" style={{ alignItems: 'center', padding: '48px 16px' }} aria-busy="true">
      <SparkLoader size={80} />
      <div className="stack gap-6" style={{ alignItems: 'center' }}>
        <strong className="display" style={{ fontSize: 24 }}>
          {title}
        </strong>
        {steps && (
          <span key={i} className="muted fade-up">
            {steps[i]}
          </span>
        )}
      </div>
    </div>
  );
}

export function CopyButton({ text, label = 'Copy' }: { text: string; label?: string }) {
  const { toast } = useApp();
  return (
    <button
      type="button"
      className="btn btn-ghost btn-xs no-print"
      onClick={() => {
        navigator.clipboard?.writeText(text).then(
          () => toast('Copied'),
          () => toast('Could not copy', 'error'),
        );
      }}
    >
      {label}
    </button>
  );
}

/** Load Google Fonts for a user brand on demand. */
export function useGoogleFonts(families: Array<{ family: string; weights: number[] }> | undefined) {
  const key = families?.map((f) => `${f.family}:${f.weights.join(',')}`).join('|');
  useEffect(() => {
    if (!families?.length) return;
    const href = googleFontsHref(families);
    if (document.querySelector(`link[data-gf="${CSS.escape(href)}"]`)) return;
    const link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = href;
    link.dataset.gf = href;
    document.head.appendChild(link);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [key]);
}

export function Empty({ title, body, action }: { title: string; body?: string; action?: ReactNode }) {
  return (
    <div className="card center stack gap-12" style={{ alignItems: 'center', padding: '48px 24px' }}>
      <Spark size={28} />
      <strong className="display" style={{ fontSize: 22 }}>
        {title}
      </strong>
      {body && <p className="muted" style={{ maxWidth: 420 }}>{body}</p>}
      {action}
    </div>
  );
}
